name: CI Github Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  ️ 
        uses: actions/checkout@v3

      # 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 安装依赖并打包
      - name: Install and Build
        run: |
          pnpm install
          pnpm run build

      # 部署
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build
